### ISSUE TITLE
Feature Request: Multiple Source Columns

### ISSUE THREAD

**Issue by pgebheim** [jonabc/linked-project-columns#12]
I'll take a look at the code to see how easy it would be to do, but it would be amazing to allow multiple source columns.

Here is the use case:
Our project consists of ~4 major project areas, which are logically separated by people working on them, etc. However, the design team works across projects and they would like visibility of all issues which require their review after deployment.

Currently, we have 1 source column in the "Trading" called "Design Review" where issues flow after they've been merged into staging. This source column is mirrored to the "Design"  project into the "Design Review" column so that the design team can ignore all the dev crap until something is ready for them to look at.

Extending this tool to taking a list of source columns would let us making other projects, but to create a unified design review process in one project.

First off: Logically this is similar to setting up multiple mirrors, except that the mirroring code wouldn't touch issues from sibling sources (where now they'd all be considered separate syncs and I believe the cards would be removed from the target).

**Comment by jonabc** [comment]
Wow, I completely missed the notification that this issue was created, I apologize for the late response @pgebheim !

This was something that was requested by a colleague of mine as well and I am about to open a PR to address this.  I'll tag you there to make sure that my proposed solution fits your needs as well as those of my colleague.

**Comment by jonabc** [comment]
This is available in the v1.1.0 release.  If you're referencing the action via `jonabc/linked-project-columns@v1` you'll pick this up automatically, otherwise you'll need to reference `@v1.1.0` 👍
